### ISSUE TITLE
Stricter TS config

### ISSUE THREAD

**Issue by vincent-psarga** [cucumber/common#1138]
## Summary

The current TS config does not raise any error when a function is declared as returning a specific type but still returns `null` or `undefined`.

This may lead to misunderstanding of the functions when relying on the signature.

## Expected Behavior

Considering the following code

```typescript
function doThings(): boolean {
  if (someSpecificCondition) { return null }

  // some more code here
  return true
}
```

Get a linter error when running `make` as 

## Current Behavior

The previous example may compile without any warning.

**Comment by aslakhellesoy** [comment]
Lat’s give this priority - ilhaving stricter type checking might reduce bugs.

**Comment by aslakhellesoy** [comment]
Reevant article: https://www.figma.com/blog/inside-figma-a-case-study-on-strict-null-checks/

**Comment by luke-hill** [comment]
@davidjgoss should this be closed and relevant issue(s), raised on the constituent repos if needed?
