### ISSUE TITLE
Attachments and logs not displayed in Example rows

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/common#1173]
Attachments attached from a hook/stepdef running as part of a Scenario Outline Examples row are not displayed by `@cucumber/react`.

Reproducible by repo mentioned in this tweet: https://twitter.com/kunalashar25/status/1301719227238289408

**Comment by Alexey-Stepanov** [comment]
Just the same issue as described by me: https://github.com/cucumber/cucumber/issues/1172
Reproduced using cucumber-ruby as well
There is one redundant "testStepFinished" section (just before the "attachment" field) when calling "attach" from hooks.rb
But attachments are displayed when calling "attach" from step definition file

**Comment by aslakhellesoy** [comment]
I just came across a possible way to render this. Have a look at the table at the bottom of [this MDN page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie):

There is a row that is "expandable", which contains more info:

<img width="1014" alt="Screenshot 2020-10-05 at 15 28 43" src="https://user-images.githubusercontent.com/1000/95092640-ca0a8600-071f-11eb-84ea-9db823c07d6c.png">

<img width="1014" alt="Screenshot 2020-10-05 at 15 29 07" src="https://user-images.githubusercontent.com/1000/95092658-cf67d080-071f-11eb-99df-3f91eae5a8a2.png">

We could do something similar for displaying attachments for example rows.

**Comment by Alexey-Stepanov** [comment]
No closing, we need this fix.
