### ISSUE TITLE
cucumber-json-formatter: ERROR: No sourceTag for

### ISSUE THREAD

**Issue by PhiliGor** [cucumber/common#1216]
## Summary
error appears when converting the message output from cucumber to json
`2020/10/15 13:05:28 ERROR: No sourceTag for aed0fa6c-a773-4b57-b895-be11bfa3866d`

## Expected Behavior
cucumber-json-formatter is able to process tags added before Examples tables

## Current Behavior
    cucumber features\test.feature --format message -o c:\Temp\messages.ndjson
    cat c:\Temp\messages.ndjson | cucumber-json-formatter --format ndjson > c:\Temp\old_json_format.json
    2020/10/15 13:05:28 ERROR: No sourceTag for aed0fa6c-a773-4b57-b895-be11bfa3866d

## Steps to Reproduce (for bugs)
create a scenario outline, having one or more examples with tags
```
Feature: tag an example
  @scenario
  Scenario Outline: tags on examples fail the test
    Given I am hungry
    Then I eat <something>
    @second_table
    Examples:
      | something |
      | fruits          |
    @second_table
    Examples:
      | something |
      | bred           |
cucumber features\test.feature --format message -o c:\Temp\messages.ndjson
cat c:\Temp\messages.ndjson | cucumber-json-formatter --format ndjson > c:\Temp\old_json_format.json
```
## Context & Motivation
as per [specification](https://cucumber.io/docs/cucumber/api/), it is possible to add tags above examples

## Your Environment
* Version used:
  * [v6.0.0](https://github.com/cucumber/cucumber/releases/tag/cucumber-json-formatter%2Fv6.0.0)
    * cucumber-json-formatter-windows-386.exe
* Operating System and version:
  * windows 10

**Comment by ChrisVereb** [comment]
I'm also seeing this with v6.0.0 cucumber-json-formatter-windows-amd64.exe on Windows Server 2016

**Comment by sandeepnagra** [comment]
I'm also seeing this issue with v6.0.0 cucumber-json-formatter (_on both MAC and Linux_). Any ETA on when will this issue be fixed?

**Comment by gbrodsky18** [comment]
I'm also seeing this issue with v6.0.0 cucumber-json-formatter (on both MAC and Linux). Is there any chance to prioritize for fixing this issue?

**Comment by sravanibattula** [comment]
I'm also seeing this issue with v6.0.0 cucumber-json-formatter (on both MAC and Linux). Do we have an ETA?

**Comment by vnaik29** [comment]
I'm also seeing this issue with v6.0.0 cucumber-json-formatter (on both MAC and Linux). Any ETA on when will this issue be fixed?

**Comment by vctqs1** [comment]
I'm also seeing this issue with v7.0.1 in Linux, Anyone already resolves it?

**Comment by aurelien-reeves** [comment]
That issue should have been fixed with [cucumber-json-formatter@17.0.2](https://github.com/cucumber/common/blob/main/json-formatter/CHANGELOG.md#1702---2021-04-22)

I did a successful test myself using the last version of cucumber-json-formatter@19.0.0. It is available here: https://github.com/cucumber/common/releases/tag/json-formatter%2Fgo%2Fv19.0.0

Could you please confirm it is working for you folks?

**Comment by vctqs1** [comment]
Fixed, thanks @aurelien-reeves

**Comment by aurelien-reeves** [comment]
You're welcome :)

**Comment by mrsenzy** [comment]
This issue still happens in 19.0.0 for linux.

**Comment by mrsenzy** [comment]
i am seeing it with [cucumber-json-formatter-linux-amd64](https://github.com/cucumber/common/releases/download/json-formatter%2Fgo%2Fv19.0.0/cucumber-json-formatter-linux-amd64)

**Comment by mpkorstanje** [comment]
@mrsenzy while it may not result in anything, opening a new issue with sufficient information to reproduce the problem in https://github.com/cucumber/json-formatter is more likely to result in a positive outcome.
