### ISSUE TITLE
messages: ndjon gherkinDocument msg skips new lines around description

### ISSUE THREAD

**Issue by grasshopper7** [cucumber/common#1224]
Not totally sure if this is an issue or desired behavior. New lines around descriptions are not shown in gherkinDocument ndjson message. 

https://github.com/cucumber/gherkin-java/blob/f8bb798cba46730877e45525d7f5433f5d47b461/testdata/good/descriptions.feature#L19

```
Scenario: empty lines around

  This description
  has an empty lines around

    Given the minimalism
```

https://github.com/cucumber/gherkin-java/blob/master/testdata/good/descriptions.feature.ast.ndjson

Relevant gherkinDocument message

_{"scenario":{**"description":"  This description\n  has an empty lines around"**,"id":"7","keyword":"Scenario","location":{"column":3,"line":19},"name":"empty lines around","steps":[{"id":"6","keyword":"Given ","location":{"column":5,"line":24},"text":"the minimalism"}]}}_

**Comment by aslakhellesoy** [comment]
This is intended behaviour of the Gherkin parser. Is it a problem? If so, why?

**Comment by grasshopper7** [comment]
Not a problem. The description text for feature and scenario in the message is included as-is. It includes the leading spaces as well as new line character with indentations. Was wondering why the wrap around lines were not present in the message.

Is it possible to similarly remove the leading and in between spaces for the description text. Would remove the parsing code required in the custom project report. Or is there a rational which I am completely missing? Thanks.

**Comment by aslakhellesoy** [comment]
> Is it possible to similarly remove the leading and in between spaces for the description text

Do you mean having it done by the Gherkin parser? Can you give a concrete example of Gherkin and the desired message output?

If you want this changed you'd have to submit a PR that implements the change for the Ruby/Go/JavaScript/Java implementations, but only after we've agreed it's a change we want.

Thanks

**Comment by grasshopper7** [comment]
Was looking for something like below, removing leading and in between spaces (in case of multi lines) in the description field.

```
Scenario: with indentation
   This is a description with indentation
```
Current message - `"description":"   This is a description with indentation"`
Desired message - `"description":"This is a description with indentation"`


```
Scenario: two lines
   This description
   has two lines and indented with spaces
```
Current message - `"description":"   This description\n   has two lines and indented with two spaces"`
Desired message - `"description":"This description\nhas two lines and indented with two spaces"`

**Comment by aurelien-reeves** [comment]
I think keeping the indentation - the spaces - in the description is on purpose. Our test suites are validating the gherkin parser that way.

Gherkin is a parser: its purpose is to parse some text, not to transform anything.

The resulting ndjson aims to provide raw data as well.

It is up to the final tool which uses those data - like formatters - to do some final transformation like trimming some white spaces if needed.

It is easier to keep too many data and remove those at the last moment than trying to retrieve some data that has been removed too early in the chain.
