### ISSUE TITLE
walkGherkinDocument/walkFeature throw error: TypeError: e is null

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/common#1273]
I'm not at liberty to share the report that reproduces the error, but I have local copy. I may update this issue with an [mcve](https://stackoverflow.com/help/minimal-reproducible-example) based on that report.

Here is a screenshot of the error from the browser console:

<img width="1089" alt="Screenshot 2020-12-09 at 12 45 52" src="https://user-images.githubusercontent.com/1000/101631982-20948900-3a1d-11eb-8db8-3e9b8fdda99f.png">

In order to fix this properly, I think it's important that we tackle #1138 - I think this and similar bugs will have a harder time hiding if we have stronger null/undefined checks.

**Comment by AlphaInfamous** [comment]
@aslakhellesoy @vincent-psarga any updates pertaining to this bug?

**Comment by aslakhellesoy** [comment]
No, we haven't looked into it yet.

**Comment by mpkorstanje** [comment]
No MCVE provided in two years. Please feel free to open a new issue with an MCVE.
