### ISSUE TITLE
[Cucumber 6.9.1] Build-In HTML report cannot present contents properly when Before/After hook failed

### ISSUE THREAD

**Issue by fireworks77** [cucumber/common#1304]
## Summary

When Before/After hook steps failed, the build-in HTML report is not readable. It throws some JavaScript errors

**Error message:**
`cucumber-pretty.bad.html:416 TypeError: Cannot read property 'sourceReference' of undefined
    at t.default (cucumber-pretty.bad.html:408)
    at Za (cucumber-pretty.html:416)
    at vc (cucumber-pretty.html:416)
    at us (cucumber-pretty.html:416)
    at cs (cucumber-pretty.html:416)
    at Xc (cucumber-pretty.html:416)
    at $c (cucumber-pretty.html:416)
    at Ps (cucumber-pretty.html:416)
    at cucumber-pretty.html:416
    at ts (cucumber-pretty.html:416)
ec @ cucumber-pretty.bad.html:416
cucumber-pretty.bad.html:416 Uncaught TypeError: Cannot read property 'sourceReference' of undefined
    at t.default (cucumber-pretty.html:408)
    at Za (cucumber-pretty.html:416)
    at vc (cucumber-pretty.html:416)
    at us (cucumber-pretty.html:416)
    at cs (cucumber-pretty.html:416)
    at Xc (cucumber-pretty.html:416)
    at $c (cucumber-pretty.html:416)
    at Ps (cucumber-pretty.html:416)
    at cucumber-pretty.html:416
    at ts (cucumber-pretty.html:416)`

## Expected Behavior
It ideally should present the report as usual, and include the before/after step failure messages.

## Current Behavior
It throws JavaScript errors and presents a blank page.
![Screenshot from 2021-01-10 16-13-40](https://user-images.githubusercontent.com/48189320/104135505-dfb2cb80-535e-11eb-89a1-044670e3c7e7.png)

~~~
~~~

## Possible Solution
Maybe a sort of HTML formatter are missing, just a guess.

## Steps to Reproduce (for bugs)
Attached a simple project to reproduce the issue. Please download and unzip the project. Then please run the CucumberTestRun class and check the */target/cucumber-reports/cucumber-pretty.html*
[cucumber.report.zip](https://github.com/cucumber/cucumber/files/5793318/cucumber.report.zip)
## Your Environment

* Version used: Cucumber 6.9.1
* Operating System and version: Linux Ubuntu 20.04
* Link to your project: 
[cucumber.report.zip](https://github.com/cucumber/cucumber/files/5793318/cucumber.report.zip)

**Comment by davidjgoss** [comment]
Hook errors are rendering fine when I test with Storybook. From the stack trace (aside: we need to enable sourcemaps in the html-formatter bundle) this is where the error is happening:

```typescript
const hook = cucumberQuery.getHook(step.hookId)
  const attachments = cucumberQuery.getTestStepsAttachments([step.id])

  if (
    stepResult.status === messages.TestStepFinished.TestStepResult.Status.FAILED
  ) {
    const location = hook.sourceReference.location
      ? hook.sourceReference.uri + ':' + hook.sourceReference.location.line
      : hook.sourceReference.javaMethod
      ? hook.sourceReference.javaMethod.className +
        '.' +
        hook.sourceReference.javaMethod.methodName
      : 'Unknown location'
```

So it looks like we haven't found the `hook` message, maybe because it wasn't emitted or because there's an id missing or mismatched. I'll check out the project and take a look at the message formatter output.

**Comment by CLehmannAquaInst** [comment]
I encounter the same problem with version 6.10.4. Is there a workaround until there is a fix?

**Comment by mpkorstanje** [comment]
@davidjgoss hooks are filtered from the html report because jvm must emit them for each scenario (resulting in an drastic increase in file size).

So yeah, hook should be nullable.

https://github.com/cucumber/cucumber-jvm/blob/main/core/src/main/java/io/cucumber/core/plugin/HtmlFormatter.java#L28

**Comment by davidjgoss** [comment]
@mpkorstanje ah thanks, that makes sense. Should be a straightforward fix then.
