### ISSUE TITLE
Break long lines in multiple lines

### ISSUE THREAD

**Issue by fslev** [cucumber/common#1423]
Right now, Cucumber reports displays long text on a single line:
![Screenshot from 2021-03-16 11-27-48](https://user-images.githubusercontent.com/17047317/111286729-2bc60900-864b-11eb-827c-bd7481c50a7d.png)

**Comment by davidjgoss** [comment]
Hi @fslev, can you add which flavour and version of cucumber you are using?

**Comment by fslev** [comment]
I am using cucumber-jvm version 6.10.2

**Comment by davidjgoss** [comment]
Sorry for late reply @fslev, you should see this fixed in the current version of cucumber-jvm - text attachments are now properly contained and scrollable horizontally.
