### ISSUE TITLE
Rename master to main on cucumber repos

### ISSUE THREAD

**Issue by davidjgoss** [cucumber/common#1507]
Small step for inclusivity. Already been done on [cucumber-jvm](https://github.com/cucumber/cucumber-jvm).

https://github.com/github/renaming

- [x] cucumber-js
- [x] cucumber-jvm
- [x] cucumber-ruby
  - [x] cucumber-ruby-core
  - [x] cucumber-ruby-wire
  - [x] cucumber-ruby
  - [x] cucumber-ruby-meta
- [x] docs (will need to change Netlify config)
- [x] godog
- [x] cucumber/common
- [x] cucumber-cpp
- [x] cucumber-rails
- [x] cucumber-electron
- [ ] [cucumber-eclipse](https://github.com/cucumber/cucumber-eclipse/issues/433)
- [x] cucumber-android
- [x] cucumber.ml

cc @mattwynne

**Comment by mattwynne** [comment]
@jaysonesmith can you help with godog?

**Comment by mattwynne** [comment]
For people with a local checkout, here's the steps you need to take:

```
# Switch to the "master" branch:
$ git checkout master

# Rename it to "main":
$ git branch -m master main

# Get the latest commits (and branches!) from the remote:
$ git fetch

# Remove the existing tracking connection with "origin/master":
$ git branch --unset-upstream

# Create a new tracking connection with the new "origin/main" branch:
$ git branch -u origin/main
```

**Comment by mattwynne** [comment]
https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main

**Comment by jaysonesmith** [comment]
> @jaysonesmith can you help with godog?

Absolutely!

**Comment by jaysonesmith** [comment]
@mattwynne I've gone through godog to update the branch and text references to main but it appears I may not have the permissions needed to actually update the repo on the GH side anymore. GH wants me to try making a PR. 😅

**Comment by mattwynne** [comment]
@jaysonesmith so you mean it woukdn't let you change the default branch? Or something else.

I've changed your org role from Member to Owner, so I think you should be good now. Please use your new powers responsibly :)

**Comment by mattwynne** [comment]
I discovered that renaming the branch using GitHub's UI (in /settings/branches) is probably the way to go. It automatically updates any PRs against the old branch, and displays a message to users letting them what to do to update their settings.

**Comment by jaysonesmith** [comment]
godog is done! 🎉 

<img width="663" alt="Screen Shot 2021-05-06 at 12 27 17 PM" src="https://user-images.githubusercontent.com/21065409/117354644-6dfb1200-ae66-11eb-94c9-f8a9a70543e1.png">

Thanks for the role update @mattwynne

**Comment by mattwynne** [comment]
@luke-hill could you take care of cucumber-rails?

**Comment by davidjgoss** [comment]
@mattwynne I lack the permissions on cucumber-js as well.

**Comment by mattwynne** [comment]
OK @luke-hill @davidjgoss I think neither of you had been added to the @cucumber/core team in github. I've fixed that - can you try again now?

**Comment by davidjgoss** [comment]
cucumber-js done!

**Comment by mvz** [comment]
Looks like someone went ahead and did this for Aruba too. Not against it, but a little surprised that I wasn't notified :confused:

**Comment by mvz** [comment]
A pull request would have been nice since the Aruba documentation refers to `master` all over the place :disappointed:.

**Comment by mattwynne** [comment]
@aslakhellesoy I'm wondering if it makes sense to do https://github.com/cucumber/common/issues/1550 before tackling the monorepo, as the subrepo stuff feels like the risky part of doing this on the monorepo, and the less of it there is to have to fix if it breaks, the better. WDYT?

**Comment by mattwynne** [comment]
These are the remaining repos that have `master` as default branch:

https://github.com/cucumber/aruba-getting-started
https://github.com/cucumber/aruba-website
https://github.com/cucumber/commitbit
https://github.com/cucumber/cucumber-android
https://github.com/cucumber/cucumber-classroom
https://github.com/cucumber/cucumber-cpp
https://github.com/cucumber/cucumber-eclipse
https://github.com/cucumber/cucumber-eclipse-update-site
https://github.com/cucumber/cucumber-eclipse-update-site-snapshot
https://github.com/cucumber/cucumber-electron
https://github.com/cucumber/cucumber-js-package-upgrade
https://github.com/cucumber/cucumber-json-testdata-generator
https://github.com/cucumber/cucumber-lua
https://github.com/cucumber/cucumber-message-upload-service
https://github.com/cucumber/cucumber-ruby-tcl
https://github.com/cucumber/cucumber-tcl-wire
https://github.com/cucumber/cucumber.io-file-generator
https://github.com/cucumber/cucumber.ml
https://github.com/cucumber/git-subrepo
https://github.com/cucumber/github-issue-stats
https://github.com/cucumber/microdata
https://github.com/cucumber/multi_test
https://github.com/cucumber/protobuf
https://github.com/cucumber/protobuf.js
https://github.com/cucumber/repo-template
https://github.com/cucumber/slack-invite-automation
https://github.com/cucumber/todo-react-typescript-subsecond

**Comment by mattwynne** [comment]
cucumber-electron and cucumber-cpp are done.

**Comment by mattwynne** [comment]
I've raised an issue in cucumber-eclipse. It looks like renaming the branch could break their CI. https://github.com/cucumber/cucumber-eclipse/issues/433

**Comment by mattwynne** [comment]
I've gone ahead and done this on cucumber-android and cucumber.ml

**Comment by mattwynne** [comment]
I think we've reached "good enough for now" on this.
