### ISSUE TITLE
Remove mono dependency from the build process

### ISSUE THREAD

**Issue by mattwynne** [cucumber/common#1532]
This is one of the pieces getting in the way of https://github.com/cucumber/cucumber-build/pull/12

Mono was historically there to let us run the Berp executable, but there may be other was to do it.

@gasparnagy is going to have a look at whether we can use the newly-added .NET 5 runtime dependency to run Berp instead, or if not what our other options are.

**Comment by aslakhellesoy** [comment]
Yeah I don’t think we need mono anymore...

**Comment by gasparnagy** [comment]
Quick check: berp in it's current form cannot be executed with .NET 5, so I need to recompile it to that platform. Unfortunately it has a dependency (for the template parser engine), that has not been updated to .NET 5. There are alternatives though, so it is possible to replace it with (hopefully) minimal changes in the razor files, but it needs a bit more time.

**Comment by gasparnagy** [comment]
Good news. I was able to upgrade berp... I want to make a few tests with cucumber, but it looks promising...

**Comment by aslakhellesoy** [comment]
Is this now fixed @gasparnagy ?

**Comment by gasparnagy** [comment]
Partly. #1542 removed the reference to mono, so now we can also remove it from the build docker image, that is yet to be done.
