### ISSUE TITLE
import io.cucumber.messages.types. can't be resolved

### ISSUE THREAD

**Issue by gitissuepost** [cucumber/common#1536]
Importing Classes from io.cucumber.messages.types gives error saying "the import cannot be resolved"

The same packages are used in some test classes of gherkin-java project. I tried importing that project and ended up with the same error. 

import io.cucumber.messages.types.Envelope;
import io.cucumber.messages.types.Feature;
import io.cucumber.messages.types.GherkinDocument;
import io.cucumber.messages.types.Pickle;
import io.cucumber.messages.types.PickleStep;
import io.cucumber.messages.types.Scenario;

* Version used: messages: 15.0.0, cucumber-core: 6.10.3
* Operating System and version: Windows 10

**Comment by mpkorstanje** [comment]
The types you are looking for are located in `import io.cucumber.messages.Messages.*`
