### ISSUE TITLE
Exception while creating a GherkinDocument Parser

### ISSUE THREAD

**Issue by gitissuepost** [cucumber/common#1544]
The types you are looking for are located in `import io.cucumber.messages.Messages.*`

_Originally posted by @mpkorstanje in https://github.com/cucumber/common/issues/1536#issuecomment-840590699_

` Parser<GherkinDocument> parser = new Parser(new GherkinDocumentBuilder(idGenerator));`

The above code ends up with exception while using these Classes from Messages class.

My Code:

```java
import io.cucumber.gherkin.GherkinDocumentBuilder;
import io.cucumber.gherkin.Parser;
import io.cucumber.gherkin.TokenMatcher;
import io.cucumber.messages.IdGenerator;
import io.cucumber.messages.Messages.GherkinDocument;

public class SampleGherkinDocumentBuilderTest {
	private final static IdGenerator idGenerator = new IdGenerator.Incrementing();

	public static void main(String[] args) {
		Parser<GherkinDocument> parser = new Parser(new GherkinDocumentBuilder(idGenerator));
		TokenMatcher matcher = new TokenMatcher();

		GherkinDocument d1 = parser.parse("Feature: 1", matcher);
		GherkinDocument d2 = parser.parse("Feature: 2", matcher);

		System.out.println(d1.getFeature().getName());
		System.out.println(d2.getFeature().getName());
	}
}
```

Help me understand what am I missing here as `Parser<GherkinDocument> parser = new Parser<GherkinDocument>(new GherkinDocumentBuilder(idGenerator));` ends up in compiler error

**Comment by aslakhellesoy** [comment]
Assuming you're using version 18.1.1 (the latest release as of today), you can find an example here:

https://github.com/cucumber/common/blob/gherkin/v18.1.1/gherkin/java/src/test/java/io/cucumber/gherkin/ParserTest.java

Please ask for this issue to be reopened if this doesn't solve your problem.

**Comment by gitissuepost** [comment]
@aslakhellesoy  : Can we please reopen this. I used the test to parse a feature file and it ended up with exception. Attached are a dump of my sample project and the exception I encounter. My requirement is to parse the feature file to manipulate that in run time. 

E.g. I have an external source where all test data are being maintained (let's say Jira/ALM). Before the test gets triggered, we have capabilities to fetch those details from the source. After that we need to add test data fetched into example section and the resultant feature will be consumed by cucumber for execution. To update the Examples section, we need to build a parser and that's where I am looking for built-in classes, if any available, which can be utilized to parse the feature and re-create it with updates.

Initial Feature:

Feature: Sample Feature
Scenario: Sample Scenario
Given I launch chrome
When I navigate to <URL>
Then I will land to page with header <PageHeader>

Updated Feature to be re-created for execution:

Feature: Sample Feature
Scenario: Sample Scenario
Given I launch chrome
When I navigate to <URL>
Then I will land to page with header <PageHeader>

Examples:
|URL|PageHeader|
|http://www.google.com|Google|

[Sample-Project Dump](https://github.com/cucumber/common/files/6488734/Sample-Parser.zip)
[Exception](https://github.com/cucumber/common/files/6488735/Exception.Outcome.txt)

**Comment by mattwynne** [comment]
@gitissuepost can you put the sample project on GitHub please, in a public repo?

**Comment by mattwynne** [comment]
The exception is:

```
Exception in thread "main" io.cucumber.gherkin.ParserException$CompositeParserException: Parser errors:
(19:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Feature: Visit career guide page in career.guru99.com'
(21:3): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Scenario: Visit career.guru99.com'
(22:5): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Given I am on career.guru99.com'
(23:7): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got '|a|b|c|'
(24:7): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got '|a1|b1|c1|'
(25:5): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'When I click on career guide menu'
(26:7): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got '|a|b|c|'
(27:7): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got '|a1|b2|c1|'
(28:5): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Then I should see career guide page'
(29:7): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got '|a|b|c|'
(30:7): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got '|a1|b1|c1|'
	at io.cucumber.gherkin.Parser.addError(Parser.java:159)
	at io.cucumber.gherkin.Parser.matchTokenAt_0(Parser.java:549)
	at io.cucumber.gherkin.Parser.matchToken(Parser.java:344)
	at io.cucumber.gherkin.Parser.parse(Parser.java:138)
	at io.cucumber.gherkin.Parser.parse(Parser.java:119)
	at io.cucumber.gherkin.Parser.parse(Parser.java:115)
	at parser.ParserTest.main(ParserTest.java:23)
```

This looks to be trying to parse some Gherkin that's different to what's shown in the comment above.

**Comment by mattwynne** [comment]
Pulled from the sample project Zip, this is the feature that fails to parse:

```
#Author: your.email@your.domain.com
#Keywords Summary :
#Feature: List of scenarios.
#Scenario: Business rule through list of steps with arguments.
#Given: Some precondition step
#When: Some key actions
#Then: To observe outcomes or validation
#And,But: To enumerate more Given,When,Then steps
#Scenario Outline: List of steps for data-driven as an Examples and <placeholder>
#Examples: Container for s table
#Background: List of steps run before each of the scenarios
#""" (Doc Strings)
#| (Data Tables)
#@ (Tags/Labels):To group Scenarios
#<> (placeholder)
#""
## (Comments)
#Sample Feature Definition Template
Feature: Visit career guide page in career.guru99.com

  Scenario: Visit career.guru99.com
    Given I am on career.guru99.com
    		|a|b|c|
    		|a1|b1|c1|
    When I click on career guide menu
    		|a|b|c|
    		|a1|b2|c1|
    Then I should see career guide page
    		|a|b|c|
    		|a1|b1|c1|

```

**Comment by mattwynne** [comment]
I'm confused about why that doesn't parse, it looks OK to me.

**Comment by mpkorstanje** [comment]
The `TokenMatcher` is language sensitive. At glance I'd say that it hasn't been configured for the right language.

**Comment by aslakhellesoy** [comment]
Yes, that feature file does not look Norwegian 🇳🇴 at all to me :-)

**Comment by mpkorstanje** [comment]
Maybe we could improve the API a bit here.

```
Parser parser = Parser.builder()
   .detectLanguageFromFeature()
   .defaultLanguage("en")
   .build()
```

Currently the `detectLanguageFromFeature` is done by Cucumber JVM by looking for the `# language: ` pragma. This has been around for so long now that perhaps we should make it part of the specification.

**Comment by mpkorstanje** [comment]
Or maybe we can some up with something that _just works_<sup>TM</sup>.

**Comment by gitissuepost** [comment]
Thank you all for your feedback. I didn't check that the TokenMatcher was initialized for Norwegian language. By setting it to "en", I am able to execute the script perfectly. However, i couldn't find any suitable method to read the step of a specific scenario. 

@aslakhellesoy : For time being I am closing this ticket. I will explore more to see if it's breaking some where and we can reopen this /log a new issue  at that time.
