### ISSUE TITLE
Looks like cucumber-json-formatter-windows-amd64 executable is unsafe to use because of threats detected in it by VirusTotal

### ISSUE THREAD

**Issue by pgundlupetvenkatesh** [cucumber/common#1556]
json-formatter: Threat Detected on cucumber-json-formatter-windows-amd64 by VirusTotal third-party online tool

## Summary
My employer recently notified me not to use cucumber-json-formatter-windows-amd64 executable as it's unsafe by VirusTotal as it scanned and determined it as a potential threat.

## Detected Threats
Please click the below link to view the threat details

https://www.virustotal.com/gui/file/0fc4a7f15a78b65648e762b77069dc420c6dc331f172f2f7fe63c1ebeeaad71a/detection

## Context & Motivation
I am trying to fix the below warning using Cucumber Standalone JSON Formatter which will be consumed by the Cucumber Reports Jenkins plugin.
```
WARNING: --format=json is deprecated and will be removed after version 5.0.0.
Please use --format=message and stand-alone json-formatter.
json-formatter homepage: https://github.com/cucumber/cucumber/tree/master/json-formatter#cucumber-json-formatter.
```

## Your Environment
* Version used: Cucumber 4.1.0, ruby 2.6.3p62
* Operating System and version: Windows 10 Enterprise 2016

**Comment by aslakhellesoy** [comment]
We've decided not to deprecate the JSON formatter since it's so widely used. If you upgrade to 6.1.0 that deprecation warning will be gone. See https://github.com/cucumber/cucumber-ruby/blob/main/CHANGELOG.md#changed-1 for details.

Regarding the virus scanner - it's a false positive.

**Comment by aslakhellesoy** [comment]
Also this: https://golang.org/doc/faq#virus

**Comment by pgundlupetvenkatesh** [comment]
> Also this: https://golang.org/doc/faq#virus

That's helpful, thanks.
