### ISSUE TITLE
Generate Ruby DTOs for messages

### ISSUE THREAD

**Issue by mattwynne** [cucumber/common#1574]
## Summary

We're currently using a plain old Ruby Hash to represent message payloads. It will be simpler for consumers if we can de-serialize the messages into simple Ruby value objects, (or DTO - Data Transfer Objects) and pass those around instead.

## Expected Behavior

API consumers should receive messages as Ruby objects instead of hashes.

## Possible Solution

See Aslak's advice [here](https://github.com/cucumber/cucumber-ruby/pull/1544#issuecomment-847734909).

**Comment by mattwynne** [comment]
@aurelien-reeves and I did some spiking on this today. We explored using https://github.com/quicktype/quicktype/ to generate the Ruby classes. It looked pretty good until we tried to run it, and discovered that the generated code has a [dependency on a very old version](https://github.com/quicktype/quicktype/pull/1385) of `Dry::Types`.

While quicktype looked like a nice idea, and might have helped us to replace the typescript and go generators too, we think that adding a dependency on a library like `Dry::Types` is too much, since many of our users will be loading Cucumber into the same process as their app, and they may be using their own version of this library.

So having explored the alternatives, it looks like building our own generator is the best solution.

**Comment by aslakhellesoy** [comment]
Good call. I also evaluated quicktype, but ended up with a custom code generator.

**Comment by aurelien-reeves** [comment]
I close this one as messages v17.0.0 brings brand new ruby DTOs :)

**Comment by mattwynne** [comment]
🎉
