### ISSUE TITLE
Translate the Gherkin Rule keyword

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/common#1578]
Last year, a new [Rule](https://cucumber.io/blog/bdd/gherkin-rules/) keyword was added to Gherkin. Please help us by adding a comment to this issue, and we'll update the parser accordingly. Example:

Norwegian (no): Regel

Obrigado!

**Comment by pzelenovic** [comment]
Serbian (Cyrillic): Правило
Serbian (Latin): Pravilo

**Comment by aslakhellesoy** [comment]
Много хвала @pzelenovic!

(In case anyone wonders - I know how to use Google Translate, but these translations should be done by humans in case we choose the wrong translation amongst many possibilities).

**Comment by Jaahquubel** [comment]
Polish (pl): Reguła.

**Comment by aslakhellesoy** [comment]
Thanks @Jaahquubel

**Comment by erendemirel** [comment]
Turkish (tr): Kural
