### ISSUE TITLE
Not able to create DataTable with TableConverter

### ISSUE THREAD

**Issue by iamgovindthakur** [cucumber/common#1620]
## Summary

Hi I have a Data like in the form of List<List< String >>
[[fName, lName, email, sex, mob, address], [Easter, Bristowe, ebristowe0@dropbox.com, F, 551-356-9751, 2894 Sutherland Park], [Raquela, MacGragh, rmacgragh1@ocn.ne.jp, F, 379-224-2320, 2599 Tennyson Trail], [Malinde, Minshaw, mminshaw2@time.com, F, 106-223-2325, 1 Old Shore Street], [Rebekah, Tommen, rtommen3@dot.gov, F, 780-243-7802, 145 Briar Crest Street], [Norby, Devil, ndevil4@booking.com, M, 101-322-0317, 5849 Vermont Way], [Halimeda, Baskwell, hbaskwell5@yellowpages.com, F, 615-791-6817, 13362 Forest Place], [Claudia, Ormshaw, cormshaw6@wunderground.com, F, 761-913-3213, 17711 Randy Trail], [Hortensia, McClenaghan, hmcclenaghan7@usnews.com, F, 141-855-3342, 3689 Old Gate Center], [Jerome, Galletly, jgalletly8@chicagotribune.com, M, 801-951-1393, 02 Monterey Lane], [Miller, Aiston, maiston9@histats.com, M, 641-793-5124, 814 Straubel Lane]]

I want the above data to get converted into DataTable with the help of TableConverter  by using code like this

```
public static DataTable.create(List<List<String>> raw, TableConverter tableConverter) {
        return new DataTable(copy(requireRectangularTable(raw)), tableConverter);
    }
```
Later I want to fetch the data from generated DataTable like this

```
for (Map<String, String> users : data.asMaps(String.class, String.class)) {
			System.out.println(users.get("email"));
		}
```

Please help me implementing the above logic. As I don't know what to give in second argument of  DataTable.create() function.
Any help will be appreciated. I searched everywhere I did not get help from a single one. And please provide the documentation of all your functions with examples so that it will be self understanding.

**Comment by mpkorstanje** [comment]
I can't really work out what you're trying to do. If you are using cucumber-jvm you shouldn't have to use any of this. You can define the list in the the step definition and Cucumber will convert the table.

```
    @Given("a datatable as a list of maps:")
    public void a_data_table(List<Map<String, String>> table){
        
    }
```    
Have a look at:

https://github.com/cucumber/cucumber-jvm/tree/main/java#data-tables
