### ISSUE TITLE
Parsing NdJson Messages in Java

### ISSUE THREAD

**Issue by sashokbg** [cucumber/common#1623]
Hello, I am spending some of my free time working on the cukedoctor project (https://github.com/rmpestano/cukedoctor) which aims to add AsciiDoc format features to cucumber.

The main idea is to parse the the JSON output of the cucumber tests and compile them to adoc pages.

The project still uses the old JSON format and I am trying to migrate it to the new cucumber messaging system.
I am however unable to find examples on how to properly parse the messages and would appreciate any guides on how to do it.

I have seen the json formatter (written in go) but I am having a very hard team reading go.
I have also seen the json schema for the messages but no examples written in Java on how to use them.

Best Regards

**Comment by aslakhellesoy** [comment]
Hi @sashokbg - I added an example in https://github.com/cucumber/common/tree/main/messages/java#readme - hope this helps.
