### ISSUE TITLE
`willBeRetried` not part of `TestStepResult`

### ISSUE THREAD

**Issue by christian-bromann** [cucumber/common#1703]
**Describe the bug**
The latest version of `@cucumber/messages` seems to mismatch with the current master branch. The `willBeRetried` property is in `master` part of the [`TestStepResult`](https://github.com/cucumber/messages-javascript/blob/master/src/messages.ts#L618) class, e.g.:

```ts
export class TestStepResult {

  @Type(() => Duration)
  duration: Duration = new Duration()

  message?: string

  status: TestStepResultStatus = TestStepResultStatus.UNKNOWN

  willBeRetried: boolean = false
}
```

However if you download latest package version it is part of `TestCaseFinished` for some reason:

```ts
export class TestCaseFinished {

  testCaseStartedId: string = ''

  @Type(() => Timestamp)
  timestamp: Timestamp = new Timestamp()

  willBeRetried: boolean = false
}
```

**To Reproduce**

**Expected behavior**
`willBeRetried` should be part of `TestStepResult`.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by luke-hill** [comment]
https://github.com/cucumber/common/blob/main/messages/CHANGELOG.md#1700---2021-07-08

It was moved as part of the latest breaking changes.

**Comment by mpkorstanje** [comment]
@luke-hill this was orginally posted in cucumber/messages-javascript.

The last sync to the subrepo was on May 20th. So I think there is another underlying cause.

@mattwynne With  https://github.com/cucumber/common/issues/1550 in mind I think some sign posts need to be updated.

**Comment by luke-hill** [comment]
Ah oki, rsync playing up then.

**Comment by mpkorstanje** [comment]
Mmh. The `master` branch is out of date. The `main` branch is up to date.

@mattwynne same problem but because of #1561 instead.

**Comment by luke-hill** [comment]
Actually I think it's the branch name. `main` seems correct: https://github.com/cucumber/messages-javascript/blob/main/src/messages.ts#L618

**Comment by christian-bromann** [comment]
@aslakhellesoy I updated the package, all looks good now, thank you team!
