### ISSUE TITLE
Add "For Each" syntax that operates over sets, to simplify "Examples" table in the case of cartesian products

### ISSUE THREAD

**Issue by lhannest** [cucumber/common#1860]
It would be nice to write a scenario like this:

```
Scenario Outline: I enjoy all the things I eat
    When I eat something that is <texture>, <colour>, <size>, and <temperature>
    Then I thoroughly enjoy it
    For each combination of
        texture in {slimy, grainy, crunchy}
        colour in {red, green, yellow, orange, purple, blue}
        size in {large, medium, small}
        temperature in {hot, room temperature, cold}
```

This could compile to the same thing as:
```
Scenario Outline: I enjoy all the things I eat
    When I eat something that is <texture>, <colour>, <size>, and <temperature>
    Then I thoroughly enjoy it
    Examples:
        | texture | colour | size | texture | temperature |
        ...
```
Where the "Examples" table has a row for each cartesian product of the above sets.

**Is your feature request related to a problem? Please describe.**
It's a small problem, but the examples table can be ugly and unreadable when we want a big cartesian product. This would improve readability in such cases.

Also, suppose I wanted to add a new column that will hold a few different values. With the "For Each" syntax it's a very small change to the file--just add one more line. With the "Examples" syntax it's a massive change to the file, and involves adding many new lines.

**Describe the solution you'd like**
Above.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by aslakhellesoy** [comment]
One of the overarching goals of Gherkin has always been to keep it simple enough that non-programmers can understand it. For this reason we have always rejected proposals to add advanced programming constructs to the language.

I consider this proposal to fall into that category, so we won't accept this.

As an alternative I would propose using a pairwise testing tool to generate a smaller table manually. See https://www.pairwise.org/ for details.

**Comment by aslakhellesoy** [comment]
I'd use [pict](https://github.com/microsoft/pict) to generate a table. If you're on MacOS you can `brew install pict`. On windows you can download `pict.exe` fro GitHub.

With your example:

model.txt:
```
texture: slimy, grainy, crunchy
colour: red, green, yellow, orange, purple, blue
size: large, medium, small
temperature: hot, room temperature, cold
```

Then, running `pict model.txt`

```
texture	colour	size	temperature
crunchy	green	large	room temperature
grainy	orange	small	room temperature
slimy	purple	large	cold
grainy	yellow	large	hot
grainy	blue	medium	cold
slimy	red	large	hot
crunchy	purple	small	hot
crunchy	red	small	cold
slimy	orange	large	hot
slimy	red	medium	room temperature
slimy	green	small	hot
slimy	yellow	small	cold
crunchy	blue	medium	hot
crunchy	yellow	medium	room temperature
crunchy	orange	medium	cold
slimy	blue	small	room temperature
grainy	red	medium	hot
grainy	blue	large	cold
grainy	green	medium	cold
grainy	purple	medium	room temperature
```

That's 20 test cases, as opposed to 216 (3*6*3*4).

You can post-process the output with `sed` to add pipes so you can paste it straight
into your feature file:

```
pict model.txt | sed "s/\t/ | /g" | sed "s/^/| /" | sed "s/$/ |/"
```

Which prints:

```
| texture | colour | size | temperature |
| crunchy | green | large | room temperature |
| grainy | orange | small | room temperature |
| slimy | purple | large | cold |
| grainy | yellow | large | hot |
| grainy | blue | medium | cold |
| slimy | red | large | hot |
| crunchy | purple | small | hot |
| crunchy | red | small | cold |
| slimy | orange | large | hot |
| slimy | red | medium | room temperature |
| slimy | green | small | hot |
| slimy | yellow | small | cold |
| crunchy | blue | medium | hot |
| crunchy | yellow | medium | room temperature |
| crunchy | orange | medium | cold |
| slimy | blue | small | room temperature |
| grainy | red | medium | hot |
| grainy | blue | large | cold |
| grainy | green | medium | cold |
| grainy | purple | medium | room temperature |
```
