### ISSUE TITLE
Cucumber report does not parse newlines

### ISSUE THREAD

**Issue by derfischmeister** [cucumber/common#1873]
**Describe the bug**
I have some multi line freeform text underneath Feature: in my .feature file. The cucumber report parses this all in one line.
Example of the .feature file:
`Feature:  New functionality
  This is a very long description
  That I want to place over multiple lines in my cucumber report
  So that it's more readable`

Result in the local report by the html-formatter:
![image](https://user-images.githubusercontent.com/97435926/149002599-40c460c9-7730-4497-978d-4e9b681f3c8d.png)

**To Reproduce**
1. Create a feature file with additional description over multiple lines beneath the feature title. See above example.
2. Run the feature file so that a report will be generated.
3. Look at the report and find out if the additional description is parsed in one line of over multiple lines.

**Expected behavior**
Additional description over multiple lines instead of one big line.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser firefox
 - Version 95.0.2

**Slack discussion**
https://cucumberbdd.slack.com/archives/C60TKS3SL/p1641377945383500

**Comment by davidjgoss** [comment]
Descirptions are treated as Markdown by the HTML formatter, and in Markdown single line breaks are expressed as two spaces at the end of a line: https://spec.commonmark.org/0.30/#hard-line-breaks

However, editors have a tendency to trim the space at the end of lines in a feature file, so this can make it hard for people to write it this way.

TBA how we address this.

**Comment by derfischmeister** [comment]
Indeed the editor has trimmed the two spaces at the end of the line. So, not a bug but a formatting thing in the editor.

**Comment by davidjgoss** [comment]
Which editor out of interest @derfischmeister?

**Comment by derfischmeister** [comment]
IntelliJ

**Comment by davidjgoss** [comment]
Same! Thanks.

**Comment by davidjgoss** [comment]
Raised this with JetBrains FWIW https://youtrack.jetbrains.com/issue/IDEA-286738
