### ISSUE TITLE
Auto-merge Renovate bot PRs

### ISSUE THREAD

**Issue by ciaranmcnulty** [cucumber/common#1938]
On another project we are using this action https://github.com/ridedott/merge-me-action

It can auto-merge PRs as long as the tests fail. It'd need to trigger based on CircleCI pass, which seems doable, then in the config of that action we need to specify the name of the bot that gets auto merged https://github.com/ridedott/merge-me-action#enable-auto-merge-for-a-different-bot

**Comment by mpkorstanje** [comment]
Did you know about:

https://docs.renovatebot.com/configuration-options/#automerge

I've set it up in `cucumber-jvm` for minor and patch versions:

https://github.com/cucumber/cucumber-jvm/blob/main/.github/renovate.json#L11

Major versions need some semver consideration so those are better done manually.

**Comment by mpkorstanje** [comment]
In fact, looks like auto merge is already enabled for this repo:

 https://github.com/cucumber/common/blob/main/.github/renovate.json#L14

**Comment by ciaranmcnulty** [comment]
Ah that probably covers it :)

**Comment by mpkorstanje** [comment]
You may want to fix your other project. :laughing:
