### ISSUE TITLE
Compiling fails if last character is backslash at example table cell 

### ISSUE THREAD

**Issue by elchupanebrej** [cucumber/common#1954]
### 🔬 How could we reproduce it?

```python
from gherkin.parser import Parser
from gherkin.pickles.compiler import Compiler

feature = r"""
Feature: Outline backslash character

    Scenario Outline: Outline with escaped backslash character
        Given I print the <string>

        Examples:
        | string |
        | bork\\ |

"""

gherkin_ast_data = Parser().parse(feature)
pickles = Compiler().compile(gherkin_ast_data)
```

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by aurelien-reeves** [comment]
Thanks again @elchupanebrej 😁

Same as #1953 : I'll check if this happens with other implementations

**Comment by brasmusson** [comment]
To be precis, it is not parsing but compiling which fails with trailing backslash.
