### ISSUE TITLE
gherkin/java: Use generated code instead of reading gherkin-languages.json

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/common#1957]
### 🤔 What's the problem you're trying to solve?

Reading `gherkin-languages.json` requires the inclusion of a json library. To avoid poluting the class path this library has to be shaded. This makes in place upgrades (e.g. for security reasons) harder.

### ✨ What's your proposed solution?

Instead of reading `gherkin-languages.json` generate the code for a list of `GherkinDialect` objects. See for example https://github.com/cucumber/ci-environment/blob/cfedf95c90052b2db812a56851daf1a6f7d1f690/java/src/main/groovy/io/cucumber/cienvironment/CiEnvironments.gsp#L7-L13

**Comment by aslakhellesoy** [comment]
I recently did this in ci-environment: https://github.com/cucumber/ci-environment/pull/22

We could use a similar approach
