### ISSUE TITLE
Cucumber-json-formatter-windows is recognized as a malicious file

### ISSUE THREAD

**Issue by OSnuszka** [cucumber/common#1974]
### 👓 What did you see?

Cucumber-json-formatter-windows is recognized as a malicious file. By the browser as well as by the antivirus.
![2022-05-09_12h37_02](https://user-images.githubusercontent.com/78599192/167393533-97763158-e15b-48ad-b017-224ee5cc1df1.png)

![2022-05-09_12h37_57](https://user-images.githubusercontent.com/78599192/167393819-7e25ab0b-f572-4891-8032-2cdf1e660978.png)

### ✅ What did you expect to see?

I would want the file to not be considered a threat.

### 📦 Which tool/library version are you using?

N/A I'm using it for cucumber/cypress reporting.

### 📚 Any additional context?

I have full confidence in the plugin, but security procedures at individual sites can cause misunderstandings - I would love to be able to use this great tool freely. I've seen old tickets about security problems (interpreting this file as a Virus) and that they were closed, but isn't there any way to correct this?

----

**Comment by mpkorstanje** [comment]
Duplicate of https://github.com/cucumber/common/issues/1681, https://github.com/cucumber/common/issues/1556. TL;DR: It's a go executable. See https://go.dev/doc/faq#virus

**Comment by mpkorstanje** [comment]
And I do believe the `json` plugin got undeprecated so you should be able to continue to use that instead of the `json-formatter`.
