### ISSUE TITLE
Move messages to stand-alone repo

### ISSUE THREAD

**Issue by mattwynne** [cucumber/common#2029]

**Comment by aurelien-reeves** [comment]
https://github.com/cucumber/messages

**Comment by aurelien-reeves** [comment]
Todo list (for at least go, java, javascript, perl, php and ruby - dotnet is ignored for now, elixir may require additional work in parallel of https://github.com/cucumber/common/pull/1952):

- [ ] Add tests as part of the CI
- [ ] Add code generation as part of dev workflow (still relying on make, but only dedicated to code generation)
- [ ] Check as part of the CI that generated code in the repo is up-to-date with the schemas
- [ ] Clean-up the repo
- [ ] Add release workflows
- [ ] Release

**Comment by mattwynne** [comment]
@aurelien-reeves thanks for all your work on this! I've had a busy few weeks and am only just picking this up. I don't quite have enough context to help with the task about synchronizing the readmes - do you mean we could copy / paste a standard README file manually into each language sub-folder? Or did you mean something more fancy and automated?

**Comment by aurelien-reeves** [comment]
@mattwynne regarding the readmes, I had no idea in mind. I just wanted to avoid missing readmes with npm or such package managers. That could be done manually.

For the release workflows:

- we don't care the for Elixir one at the moment: the actual implementation is not maintained, outdated, and unused. The next one is still WIP
- I am pretty sure we already have some Perl release workflow somewhere
- For PHP, this is based on git tags, like go-lang. This is using a sub-repo at the moment
