### ISSUE TITLE
Revise supported NodeJS versions

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/common#2141]
### 🤔 What's the problem you're trying to solve?

We are currently supporting a smattering of Node.js versions between 12.x and 17.x.  However currently 14.x is the oldest supported version and 18.x the newest. This means that on one end we are falling of the bleeding edge of Node and will not be able to spot problems early. On the other side we are running into problems where packages no longer support Node.js 12.

https://endoflife.software/programming-languages/server-side-scripting/nodejs

### ✨ What's your proposed solution?

Update a whole bunch of Ci files? 

### ⛏ Have you considered any alternatives or workarounds?

Do nothing until it breaks.

**Comment by davidjgoss** [comment]
FWIW cucumber-js will release a major version in January that drops node 12 support, at that point all the libraries can safely follow suit.

**Comment by mpkorstanje** [comment]
Cheers!

14 is also going to drop off support soonish.

And to keep the size of the CI matrix under control I think it would also be sensible to only test against the LTS versions (so 16, 18).

**Comment by davidjgoss** [comment]
cucumber.js 9.0.0 is out and so our libraries can freely remove Node.js 12 support now. I'm happy to pick that up.
