### ISSUE TITLE
release cucumber-ruby and friends using latest polyglot-release

### ISSUE THREAD

**Issue by mattwynne** [cucumber/common#2144]
We're due an 8.1 release of cucumber-ruby

This will need us to fix up the CHANGELOGs and test out `polyglot-release` on `cucumber-ruby` and its dependencies.

**Comment by luke-hill** [comment]
Marking this as completed. The changelog is updated. The polyglot release tool works well, the releasing doc is now updated in MAIN, more releases are coming soon in patch updates to tidy up some code. I'm back in.

Next step/s would be to do the same on alternative repos such as rails, but I don't anticipate any issues

**Comment by mattwynne** [comment]
Sweet, thanks for your work getting this rolling Luke
