### ISSUE TITLE
Slack Unavailable

### ISSUE THREAD

**Issue by sashokbg** [cucumber/common#2148]
Trying to access the community slack at https://cucumberbdd-slack-invite.herokuapp.com/invite
but I get an "Error:Error: certificate has expired" as soon as post my email.

Who should we notify ?
Thank you for your help

**Comment by davidjgoss** [comment]
Thanks for reporting - I’ve flagged this up to the admins of our Slack and will post further updates here.

**Comment by Jo-Laing** [comment]
Matt provided a work around for this.

Integrated [https://communityinviter.com](https://protect-us.mimecast.com/s/xB5JCmZjk8CAvYRvTGKlV1?domain=communityinviter.com) into our Slack and fixed the link on [https://cucumber.io/docs/community/get-in-touch/] to point to it.

**Comment by arietis** [comment]
FYI, there are still some pages using the old link, it took me some time to find the new one.

**Comment by luke-hill** [comment]
@arietis if you spot any links that are incorrect please feel free to edit them as a PR. You should be able to do this on the docs site by clicking at the bottom.

For anything on Github you should be able to click edit on the md file
