### ISSUE TITLE
Use arguments in scenario outline to describe test name

### ISSUE THREAD

**Issue by BeyerMart** [cucumber/common#2149]
### 🤔 What's the problem you're trying to solve?

I use `Scenario Outline` to define examples for the same test. However the tests are then all called the same, as the example argument is the only thing differnt and it is only used in one `When` statement.

### ✨ What's your proposed solution?

I dont want to write a new scenario per test, it would be great, if the `Scenario Outline` would accept arguemts as the `When` statement does. Some syntax like
```
Scenario outline: Successfully add a "<argument>" user
Given ....
When I add a new "<argument>" user
Then I assert the new created user

Examples:
| argument |
| super |
| default | ...
```

### ⛏ Have you considered any alternatives or workarounds?

Currently there are two options. Write a scenario per test, even if the complete tests only dependes on one variable and describe the variable in the scenario (making no proper use of the variable) or write a very generic Test scenario. Then the differntiation between each run are only the Number behind Examples.

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by davidjgoss** [comment]
> if the Scenario Outline would accept arguemts as the When statement does

Have you tried this? I'm pretty certain it works like this already. We might just need an update to the docs here.

**Comment by luke-hill** [comment]
One thing to bear in mind is this sometimes can trip up on reporters. But this functionality 100% exists.

I personally don't advocate this, but there's nothing stopping you doing it. I would use something like

> Scenario Outline: Successfully add a variety of user-types

**Comment by BeyerMart** [comment]
Great. Thank you.
I didn't manage to get the argument working in the Scenario Outline, but follwoing your input, I will rename my test scenario to be more generic.
