### ISSUE TITLE
how to run prallel all the scenario outline methods with Examples but the test data are in the excel file 

### ISSUE THREAD

**Issue by saro011** [cucumber/common#2155]
how to run prallel all the scenario outline methods with Examples but the test data are in the excel file and how to read and used in the scenario outline methods to run in pralllel mode  can you pls hellp me @mattwynne

**Comment by mattwynne** [comment]
Sorry, this isn't currently supported. It would require pretty major changes to Gherkin to be able to read examples from an excel file.
