### ISSUE TITLE
Cucumber html report screen is blur and couldn't able to access the report 

### ISSUE THREAD

**Issue by lavanya-vnix** [cucumber/common#2159]
Using cucumber-js automation testing, after all test cases run html report screen is not visible properly and looks like blur screen action couldn't perform on it. 
1. Imported - `
const fs = require('fs');
const path = require('path');
const reporter = require('cucumber-html-reporter');

2. In package.json using version -  "cucumber-html-reporter": "^7.1.0"

3. Command to run - "sudo npx cucumber-js features/ -f json:test/report/cucumber_report.json && node index.js"

![image](https://github.com/cucumber/common/assets/50191833/61d54d53-d5ec-4f87-a8b1-fbff7666e6ab)

Can anyone help me to fix this issue?

**Comment by mpkorstanje** [comment]
I think you're in the wrong project. You probably meant https://github.com/gkushang/cucumber-html-reporter.
