### ISSUE TITLE
Support for triggering/transforming parameterTypes in data table 

### ISSUE THREAD

**Issue by k02pradeep** [cucumber/common#2160]
### 🤔 What's the problem you're trying to solve?
ParameterType works well when using parameter type in the step definitions.
When the step has data table argument, then based on the column Id ( row[0] entries) , data should be transformed based on the parameterTyep( columnId in this case).

### ✨ What's your proposed solution?
DataTable  model should support new method to return the transformed data.

### ⛏ Have you considered any alternatives or workarounds?
Utilities can be created used for this. but it would require duplicating the logic  code for parameterType.
This would again increase the complexity within the step definition.

### 📚 Any additional context?
DataTable constructor can take second argument for expression and add new method called transformed() which would do return return the transformed data after applying parameterType transformations. 

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by davidjgoss** [comment]
Other maintainers might feel differently, but I don’t think is something we would add to Cucumber. You an always extend/wrap DataTable to do what you need though.

**Comment by mpkorstanje** [comment]
There are [many ways a data table could be mapped to an object ](https://github.com/cucumber/cucumber-jvm/tree/main/datatable), but using parameter types would be a conceptual mismatch.

Anyway, I think it would be more useful to start a feature request from a concrete real world example. I.e. the problem you're trying to solve, not the solution you imagine.
