### ISSUE TITLE
How to get Feature File commented lines in Cucumber Json Test Report

### ISSUE THREAD

**Issue by rummitta** [cucumber/common#2163]
In Cucumber version 1.2.5, comments used to appear in test report json:

However, in our framework, we upgraded to Cucumber version 5.7.0 and now we are not able to see the comments in test report.

This is causing lot of trouble for our users - who have used comments to express lot of information about the test case they are trying to test. Please let us know how to get back the comments in the cucumber report - so that subsequently, we can show the comments in the report generated by our framework.

We are using selenium java based framework. any pointers will be helpful.

**Comment by rummitta** [comment]
Attaching the cucmber json report before (with comments) and after (missing comments)
[FeatureFileWithSel4.txt](https://github.com/cucumber/common/files/14448198/FeatureFileWithSel4.txt)
[FeaturefilebeforeSel4.txt](https://github.com/cucumber/common/files/14448200/FeaturefilebeforeSel4.txt)

**Comment by mpkorstanje** [comment]
Out of curiosity, the latest version of Cucumber JVM is v7.15.0. Why are you upgrading only to v5.7.0? 

And I don't think there is a way to get those comments back using the current json formatter. The change in architecture between v1 and v2 was pretty drastic. And one of the changes, is that to wit comments are no longer associated to an element.

You didn't describe your setup in much detail, but assuming your report is completely custom, you could consider building your report based on Cucumber Messages instead. The `GherkinDocument` message has all the comments. 

[Cucumber v6 introduced a messages format](https://github.com/cucumber/cucumber-jvm/blob/main/release-notes/v6.0.0.md#message-formatter-to-replace-the-json-formatter) and we're slowly migrating the cucumber provided plugins to that. For example see the [cucumber-junit-xml-formatter](https://github.com/cucumber/cucumber-junit-xml-formatter) and [html-formatter](https://github.com/cucumber/html-formatter) already use the message protocol.

If your report is made by another open source tool, you may want to consider migrating that tool to use messages.

**Comment by rummitta** [comment]
Hi Team,
Tried adding Cucumber options like this:
![image](https://github.com/cucumber/common/assets/142016616/f818e0bb-879c-4ff9-8816-2f7bab139cec)
Also tried setting it in Cucumber options pojo and then setting it in pair:
![image](https://github.com/cucumber/common/assets/142016616/ebfd1e3f-8d29-4226-9ffd-201209055aee)
It is showing the plugin correctly in cucumber options printed in the logs
![image](https://github.com/cucumber/common/assets/142016616/fc856eb5-ab9d-4a3a-a1c5-d8670a8d370f)
However, there is no such json file as cucumber.json or no such html file as cucumber.html in the resources folder. The folder specified looks like this
![image](https://github.com/cucumber/common/assets/142016616/bc4f36da-e2e8-4d68-81e9-8301dabd1881)
In the final.json file, comments are not present - other step details are present:
![image](https://github.com/cucumber/common/assets/142016616/f72ef5b1-9a18-43cc-82df-06cc234a3e7a)
Please let me know how to use this plugin format to get the comments in the report. This is very critical for our clients.

**Comment by mpkorstanje** [comment]
I can't make much sense of your reply. I was looking for an explanation of how you use the output of the `.json` file.

So just to restate this for clarity.

1. The Json formatter does not retain the comments for any version of Cucumber after v1.

2. Should you want to get the comments back, they're available as part of [the message format](https://github.com/cucumber/messages) introduced in v6. You can consume the messages by writing your own plugin.

3. For hints on consuming the message format, I would recommend looking at the implementation of the  [cucumber-junit-xml-formatter](https://github.com/cucumber/cucumber-junit-xml-formatter) and [html-formatter](https://github.com/cucumber/html-formatter) and their usage in the source code of Cucumber-JVM.

**Comment by rummitta** [comment]
Was able to get the comments inside a cucumber generated ndjson file... However, if my FF has 3 scenarios and all of them have different set of comments, the ndjson file generated seem to have all the comments put together - without distinguishing which comment belongs to which scenario. This is not helping in the correct test report generation. 
Also the ndjson file generated is too huge - for just 3 scenarios (each scenario having 6-7 steps), the ndjson file is 572 KB. In our client's case, since each scenario itself has as many as 60-80 steps, the corresponding ndjson file is likely to cause issues. Is there any other way to generate a smaller file which has comments in the correct position.
![image](https://github.com/cucumber/common/assets/142016616/dc7e1652-2721-443b-a205-ed7e09d7731d)

**Comment by mpkorstanje** [comment]
> However, if my FF has 3 scenarios and all of them have different set of comments, the ndjson file generated seem to have all the comments put together - without distinguishing which comment belongs to which scenario. This is not helping in the correct test report generation.

The design of the Gherkin parser changed and comments are no longer associated with scenarios. I can't immediately find the associated change with the reasoning though.

Currently you will have to re-associate them yourselves. 

> Also the ndjson file generated is too huge - for just 3 scenarios (each scenario having 6-7 steps), the ndjson file is 572 KB. 

The bulk of the output is made up of step definitions, hooks and parameter types which re-instantiated for every scenario. This unfortunately can not be fixed until https://github.com/cucumber/cucumber-jvm/issues/2035 gets resolved. Possibly through https://github.com/cucumber/cucumber-jvm/issues/2279 which is a major undertaking. In the mean time you could filter hooks, step definitions and parameter type messages from the output as done by the html formatter here:

https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-core/src/main/java/io/cucumber/core/plugin/HtmlFormatter.java#L25-L31

**Comment by mpkorstanje** [comment]
I'm assuming you've figured things out. If not, feel free to ask more questions.
