### ISSUE TITLE
We're currently locked out of our npm account

### ISSUE THREAD

**Issue by mattwynne** [cucumber/common#2164]
We need to be able to use email for 2FA, and we currently don't have access to the cukebot@cucumber.io email address.

See #2165 for root cause.

**Comment by mpkorstanje** [comment]
We're back in. Credentials are in Keybase.

**Comment by mattwynne** [comment]
Great. @mpkorstanje I think it would be better to keep credentials like this in 1Password from now on.

**Comment by mpkorstanje** [comment]
Oops typo. They're in 1 password. Key base can't do MFA.
