### ISSUE TITLE
We don't have access to the cukebot@cucumber.io email address

### ISSUE THREAD

**Issue by mattwynne** [cucumber/common#2165]
Right now, the cukebot@cucumber.io email address doesn't forward on to the team.

**Comment by mattwynne** [comment]
Smartbear's rules are preventing these emails being forwarded because the email doesn't originate from an allow-list. Frank is looking into it for us.

**Comment by mpkorstanje** [comment]
Mails are being forwarded to the core team again.

**Comment by mpkorstanje** [comment]
Forwarding is discussed in https://github.com/cucumber/common/issues/2166.

**Comment by mpkorstanje** [comment]
Forwarding has been resolved.
