### ISSUE TITLE
Slack inviter is broken

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/common#2168]
### 👓 What did you see?

From @sebrose I received this via LinkedIn: “I tried to join the community slack but it states TOKEN REVOKED”
The person was using the process documented in https://cucumber.io/docs/community/get-in-touch/#slack

**Comment by mpkorstanje** [comment]
@mattwynne you're the workspace owner, I don't have sufficient permissions to dig into this.

**Comment by mattwynne** [comment]
@mpkorstanje from what I can see you're also a workspace admin.

<img width="1029" alt="Screenshot 2024-03-30 at 11 09 52 AM" src="https://github.com/cucumber/common/assets/19260/72c84e1d-620b-4ca8-adfc-9872aec1018d">

From a brief look at this, it seems like it's probably a symptom of our Slack account being downgraded, that there's a limit on the number of "apps" of which https://communityinviter.com counts as one.

I've removed a few, and it seems I was able to add the community inviter integration again.

**Comment by mattwynne** [comment]
@sebrose could you ask your friend to try again?

**Comment by mpkorstanje** [comment]
I'm an admin, but not an owner. And that's the level needed to deal with plugins.

**Comment by mattwynne** [comment]
> I'm an admin, but not an owner. And that's the level needed to deal with plugins.

Ah I didn't spot that. OK I've made you a Workspace Owner. I did the same for @davidjgoss while I was at it.

**Comment by mpkorstanje** [comment]
Okay. It looks the token the inviter used is expired. The app doesn't have a way to reset it. Slack does offer the ability to send invite links, but they can only be used by a limited number of people.

**Comment by mpkorstanje** [comment]
I've mailed community inviter people. Let's see what comes of that.

**Comment by mattwynne** [comment]
We could use "share an invite link" from https://slack.com/help/articles/201330256-Invite-new-members-to-your-workspace for now. It will need updating once we've had 400 sign-ups though.

**Comment by mattwynne** [comment]
It might be worth a Slack admin other than me visiting https://communityinviter.com/, connecting to our Slack, creating a URL and testing it out. Maybe my account's token has gone stale somehow.

**Comment by mpkorstanje** [comment]
> It might be worth a Slack admin other than me visiting 

Did that already.

**Comment by mpkorstanje** [comment]
Didn't try deleting the inviter and trying again. But let's hold off on that until the people behind the inviter can mail back.

**Comment by mpkorstanje** [comment]
This has been fixed a while ago.
