### ISSUE TITLE
Can't register for slack for cuke

### ISSUE THREAD

**Issue by Johnlon** [cucumber/common#2169]
### 🤔 What's the problem you've observed?

When I type in my email on your registration page I get.   An error like..

API token expired

Is that app broken?

Thanks John

**Comment by mpkorstanje** [comment]
Duplicate of #2168. As a work around you can use https://join.slack.com/t/cucumberbdd/shared_invite/zt-2i0fvyv35-PgrGAwIx3L~lFngzWkb86Q for now.
