### ISSUE TITLE
Add property tag into Junit report when running Cucumber tests

### ISSUE THREAD

**Issue by kakarasiri** [cucumber/common#2200]
### Discussed in https://github.com/orgs/cucumber/discussions/2199

I would like to add **<property>** tag into junit report. 
Is it possible for doing that ? or Is there any plugin that we can used ? 

TestRunner.scala 
`@RunWith(classOf[Cucumber])
@CucumberOptions(
  features = Array("classpath:features/"),
  glue = Array("steps"),
  plugin = Array(
    "pretty",
    "html:target/test-reports/cucumber/cucumber.html",
    "json:target/test-reports/cucumber/cucumber.json",
    "junit:target/test-reports/cucumber/cucumber-results.xml",
  ),
)`

Current cucumber-results.xml: 
```
<testsuite>
    <testcase>
        </system-out>
        </system-out>
    </testcase>
</testsuite>
```

What I would like to have: 
```
<testsuite>
    <testcase>
        **<properties>
            <property name="" value=""/>
        </properties>**
        </system-out>
        </system-out>
    </testcase>
</testsuite>
```</div>

**Comment by mpkorstanje** [comment]
Let's finish the discussion before starting a feature request.
