### ISSUE TITLE
Screenshot inside multiple-cucumber-html-reporter says plugin not supported when opened|| playwright || typescript

### ISSUE THREAD

**Issue by Rudra-Pratap11** [cucumber/common#2206]
### 👓 What did you see?

I tried many solutions but still the image is not opening when report is opened
I am using cucumber playwright & typescript

### ✅ What did you expect to see?

Image should open

### 📦 Which tool/library version are you using?

"dependencies": {
    "@cucumber/pretty-formatter": "^1.0.0",
    "date-fns": "^3.6.0",
    "exceljs": "^4.4.0",
    "latest": "^0.2.0",
    "moment": "^2.29.4",
    "multiple-cucumber-html-reporter": "^3.7.0",
    "read-file": "^0.2.0",
    "rimraf": "^5.0.9",
    "ts-node": "^10.9.1",
    "xlsx": "^0.18.5"
  },
  "devDependencies": {
    "@cucumber/cucumber": "^10.8.0",
    "@playwright/test": "^1.40.1",
    "@types/chai": "^4.3.5",
    "@types/xlsx": "^0.0.36",
    "allure-playwright": "^2.9.2",
    "chai": "^4.4.1",
    "experimental-allure-playwright": "0.0.3",
    "playwright": "^1.45.3",
    "winston": "^3.13.1"

**Comment by mpkorstanje** [comment]
The `multiple-cucumber-html-reporter` isn't made here. You can look up the package on NPM to see who makes it.

You'll also want to include enough information to reproduce the problem you're having.
