### ISSUE TITLE
gherkin/javascript: Tags aren't inherited by children

### ISSUE THREAD

**Issue by ChrisBAshton** [cucumber/common#417]
## Summary

[According to Cucumber docs](https://docs.cucumber.io/cucumber/api/#tag-inheritance):

> Tags are inherited by child elements.
> Tags that are placed above a Feature will be inherited by Scenario, Scenario Outline, or Examples.
> Tags that are placed above a Scenario Outline will be inherited by Examples.

## Expected Behavior

Given the following feature file:

```feature
@foo
Feature: Foo

  @bar
  Scenario Outline: bar
    Given <baz>

  @baz
  Examples:
    | baz |
    | 123 |
```

I would expect the following outputs when checking the `tags` property on each respective element:

* Feature: `@foo`
* Scenario Outline: `@foo @bar`
* Examples: `@foo @bar @baz`

## Current Behavior

What I'm actually seeing is this:

* Feature: `@foo`
* Scenario Outline: `@bar`
* Examples: `@baz`

For example, when I `console.log(scenario.examples[0].tags)`, I get `[{"type":"Tag","location":{redacted},"name":"@baz"}]`.

## Context & Motivation

I have faced this issue when trying to implement [Tag support for cypress-cucumber-preprocessor](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/58#pullrequestreview-130325624), which uses `gherkin` NPM module as a dependency.

We've successfully added Tag support but the code is quite messy; inheriting tags would mean we can avoid a lot of duplicate tag checking and let things cascade gracefully.

We can potentially [combine parent/child tags in application code](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/46/files#diff-f5c39eda58443a732e3f41ef8fb55a37R23), but this feels like it's going against the Gherkin spec and that this should be happening at a lower level.

## Your Environment

* gherkin NPM module v5.0.0
* Node v9.11.1
* NPM v5.6.0
* macOS Sierra 10.12.3

**Comment by aslakhellesoy** [comment]
The AST you get from the parser represents the structure of the input document. No tag inheritance is applied here.

The inheritance is applied by the compiler, which transforms an AST into a simpler "pickle" structure.

Try it out: `./node_modules/.bin/gherkin-javascript f.feature --no-source --no-ast | jq .`

**Comment by aslakhellesoy** [comment]
So - I think you should use the output produced by the compiler rather than the AST produced by the parser.

Much simpler, and most of the processing you're likely to need is already done for you.

**Comment by ChrisBAshton** [comment]
Understood - thanks for the response!
