### ISSUE TITLE
don't run lint-fix no CI

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/common#933]
Noticed for some javascript projects we are running lint-fix on CI. We should be running `lint` only as otherwise lint-fix may auto-fix something but we have nothing ensuring that gets committed. Alternatively we can run lint-fix if we have some other check that there is no uncommitted changes after running the commands.

**Comment by luke-hill** [comment]
Individual languages can now implement this how they want. Ruby is fine and I think other languages are good too. Suggest this gets re-created if further issues are needed to be amended.

cc/ @charlierudolph
