### ISSUE TITLE
Re-enable ruby cck

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/common#960]
It was disabled recently because it won't pass until cucumber-ruby is updated to use the latest messages. Let's wait to do this until all the open messages issues/PRs have landed on master and we've made a new monorepo release.

**Comment by vincent-psarga** [comment]
It'll have to wait for the next release of `cucumber-ruby` as this uses the released gems.

**Comment by aslakhellesoy** [comment]
Bump @vincent-psarga

**Comment by aslakhellesoy** [comment]
Bump @vincent-psarga

**Comment by aslakhellesoy** [comment]
We should move `compatibility-kit/ruby` into the cucumber-ruby repo and run there. A failure in the ruby cck is a failure of cucumber-ruby, not the monorepo.

We can use the same approach as in Cucumber-JVM to copy over the golden messages:
https://github.com/cucumber/cucumber-jvm/blob/fa9085425282d1eacfc42eed4eee9e1b004ea9f4/Makefile#L21-L30

**Comment by aslakhellesoy** [comment]
Reopening this again since it fails the build for some reason. We need to move this out of the monorepo and into cucumber-ruby.

**Comment by luke-hill** [comment]
Done above
