### ISSUE TITLE
Remove json-schema as a dev dependency

### ISSUE THREAD

**Issue by vincent-psarga** [cucumber/common#999]
In #998, I've added `json-schema` as a dev dependency in all javascript modules so we would be able to run `eslint` again.
As soon as there's a new release of `eslint` that fixes it, we should remove this dependency.

Note: I've added the Slow burner tag, not knowing when the next release would occur.

**Comment by luke-hill** [comment]
@davidjgoss guessing this is a js specific issue?

**Comment by davidjgoss** [comment]
We have no devDependencies of json-schema in the packages I've just looked through, so I think this issue has come out in the wash.
